In [2]:
import numpy as np

In [7]:
# 1
u = np.full((2,3), 2)
u

array([[2, 2, 2],
       [2, 2, 2]])

In [6]:
# 1.1
np.einsum("ij->j", u)

array([4, 4, 4])

In [8]:
# 1.2
np.einsum("ij->i", u)

array([6, 6])

In [13]:
# 2

import torch
x = torch.rand (4 , 4 )
y0 = torch.rand ( 5 )
y1 = torch.rand ( 4 )
z0 = torch.rand (3 , 2 , 5 )
z1 = torch.rand (3 , 5 , 4 )
w = torch.rand (2 , 3 , 4 , 5 )
r0 = torch.rand (2 , 5 )
r1 = torch.rand (3 , 5 , 4 )
r2 = torch.rand (2 , 4 )
s0 = torch.rand (2 , 3 , 5 , 7 )
s1 = torch.rand ( 11 , 3 , 17 , 5 )

In [35]:
# identity
a0 = y0.clone()
a1 = x.clone()
a2 = z0.clone()

# permute
b0 = x.T
b1 = x.T
b2 = z0.permute(1,2,0)
b3 = z0.permute(2,0,1)
b4 = w.permute(2,1,0,3)
b5 = w.permute(0,1,3,2)
b6 = w.permute(2,1,0,3)

# trace
c = torch.trace(x)

# sum
d0 = torch.sum(x)
d1 = torch.sum(z0)
d2 = torch.sum(w)

# sum axis
e0 = torch.sum(z0, dim=0)
e1 = torch.sum(z0, dim=1)
e2 = torch.sum(z0, dim=2)

# matrix - vector
f0 = r0.matmul(y0)
f1 = torch.matmul(r1, y1.unsqueeze(-1)).squeeze(-1)

# vector - vector outer product
g0 = torch.outer(y0, y1)
g1 = torch.outer(y0, y1).unsqueeze(-1).unsqueeze(-1) * torch.outer(y0, y1).unsqueeze(0).unsqueeze(0)

# batch mm
h0 = torch.matmul(z0,z1)
#h1 = torch.matmul(z1.permute(0,2,1), z0)


# bilinear
#i = torch.bmm(r0.unsqueeze(1), torch.bmm(r1, r2.unsqueeze(2))).squeeze(2)

# tensor contraction
#j = torch.einsum('pqrs , tqvr - > pstv' , s0 , s1 )


In [35]:
# Question 4: Programmatic Access
import os
import openai

from datasets import load_dataset

train = load_dataset("boolq", split="train[:100]")
test = load_dataset("boolq", split="validation[:100]")


Found cached dataset boolq (/Users/michaelzakariaie/.cache/huggingface/datasets/boolq/default/0.1.0/bf0dd57da941c50de94ae3ce3cef7fea48c08f337a4b7aac484e9dddc5aa24e5)
Found cached dataset boolq (/Users/michaelzakariaie/.cache/huggingface/datasets/boolq/default/0.1.0/bf0dd57da941c50de94ae3ce3cef7fea48c08f337a4b7aac484e9dddc5aa24e5)


False

In [98]:
import random

#train[0]
prompt = " "

for i in range(8):
    if i % 2 == 0:

        choice = random.randint(0, 99)
        while train[choice]['answer'] == True:
            choice = random.randint(0, 99)
        
        #prompt += train[choice]['question'] + " " + train[choice]['passage'] + " " + str(train[choice]['answer']) + " "
        prompt += train[choice]['question'] + " " + str(train[choice]['answer']) + " "
        
    else:
        choice = random.randint(0, 99)
        while train[choice]['answer'] == False:
            choice = random.randint(0, 99)
        
        prompt += train[choice]['question'] + " " + str(train[choice]['answer']) + " "
    

In [112]:
openai.api_key = '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'

score = 0
for i in range(30):

    response = openai.Completion.create(
      model="text-davinci-003",
      prompt=prompt + " " + test[i]['question'],
      temperature=0.7,
      max_tokens=256,
      top_p=1,
      frequency_penalty=0,
      presence_penalty=0
    )

    generated_text = response.choices[0].text
    print(generated_text)
    
    if str(test[0]['answer']) in generated_text:
        score += 1

print("Accuracy: " + str(score/30))


 False
 False
 False
 True
 True
 True
 True
 False
 Yes
 False
 False
 False
 False
 False
 True
 False
 False
 True
 False
 True
 False
 True
 thing False
 True
 fire 7 tablet True
 False
 True
 to hotwire it False
 True
 False
Accuracy: 0.5666666666666667


In [111]:
# Question 5


import requests

url = "https://api-inference.huggingface.co/models/bigscience/bloomz"

headers = {
    "Content-Type": "application/json",
    "Accept": "application/json",
    "Authorization": "Bearer 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"
}

score = 0
for i in range(100):
    
    payload = {
        "inputs": prompt + " " + test[i]['question'],
        "options": {
            "temperature": 0.3,
            "max_length": 50
        }
    }
    response = requests.post(url, headers=headers, json=payload)
    try:
        print(response.json()[0]['generated_text']) # !@!
        
        resp_end = response.json()[0]['generated_text'][-8:]
        print(response.json()[0]['generated_text'])
        #print(resp_end)
        if str(test[i]['answer']) in resp_end:
            score += 1
    except: pass
    

print("Accuracy: " + str(score/100))
    #print(response.json()['generated_text'])
    # if str(test[0]['answer']) in generated_text:
    #     score += 1


# GPT used to debug API format


 was the leaning tower of pisa built leaning False does the world cup final go to penalties True is post office and royal mail the same False is jack sikma in the hall of fame True has any nfl team played the superbowl at home False can liquid latex be used as an adhesive True is saline and sodium chloride the same thing False do texas state troopers have to wear hats True  does ethanol take more energy make that produces False is the world cup final False
 was the leaning tower of pisa built leaning False does the world cup final go to penalties True is post office and royal mail the same False is jack sikma in the hall of fame True has any nfl team played the superbowl at home False can liquid latex be used as an adhesive True is saline and sodium chloride the same thing False do texas state troopers have to wear hats True  does ethanol take more energy make that produces False is the world cup final False
 was the leaning tower of pisa built leaning False does the world cup final go

' is the movie the wall a true story False does lex luthor know who superman is in smallville True several cranial nerves innervate structures of the tongue False is lord of the rings after the hobbit True will there be a new season of cutthroat kitchen False has anyone scored 6 goals in one game True is post office and royal mail the same False can you have a right and left bundle branch block True is pain experienced in a missing body part or paralyzed area'